spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: 1
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: com.thesis.service.config.CustomPostgreSQLDialect
        enable_lazy_load_no_trans: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  mvc.format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
    time: HH:mm:ss
  jackson.default-property-inclusion: NON_NULL

logging.level.org:
  hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  springframework:
    web.filter.CommonsRequestLoggingFilter: INFO
    web: TRACE
# logging.file: D:/log/myapp.log

firebase.config.adminSdkPath: firebase-config.json

host: http://localhost:3000

server.servlet.context-path: /api