spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 1
    initialization-mode: always 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: com.thesis.service.config.CustomPostgreSQLDialect

server.servlet.context-path: /api
jwt.secrect: "thesis"
