spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-193-113-223.compute-1.amazonaws.com:5432/dat8ap7r4qr89j
    username: vrhwfhxfqlxdip
    password: bc7f7e681cf96e905afc1a28e77aa7ef623c49b81fae4dec58f0527b8a25bdf7
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: com.thesis.service.config.CustomPostgreSQLDialect
        enable_lazy_load_no_trans: true
  mvc.format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
    time: HH:mm:ss
  jackson.default-property-inclusion: NON_NULL

logging.level.org:
  hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  springframework:
    web.filter.CommonsRequestLoggingFilter: INFO
    web: TRACE
# logging.file: D:/log/myapp.log

firebase.config.adminSdkPath: firebase-config.json

host: https://datai-thesis-web.herokuapp.com

server.servlet.context-path: /api