spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 1
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: com.thesis.service.config.CustomPostgreSQLDialect
        enable_lazy_load_no_trans: true

logging.level.org.springframework:
  web.filter.CommonsRequestLoggingFilter: INFO
  web: TRACE
# logging.file: D:/log/myapp.log

firebase:
  config.adminSdkPath: firebase-config.json

server.servlet.context-path: /api
jwt.secrect: "thesis"
