
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/semesters?direction=DESC
Content-Type: application/json
X-auth: {{backDoorToken}}

### create
POST {{http}}{{host}}{{port}}{{base-url}}/semesters
Content-Type: application/json
X-auth: {{backDoorToken}}

{
  "name": "221",
  "registerTopicStart": "2021-08-17T00:12:00"
}

### setting current semester
PUT {{http}}{{host}}{{port}}{{base-url}}/semesters/current?id=4
Content-Type: application/json
X-auth: {{backDoorToken}}
