
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/semesters?direction=DESC
Content-Type: application/json
X-auth: {{backDoorToken}}

###  get by example
POST {{http}}{{host}}{{port}}{{base-url}}/semesters/example
Content-Type: application/json
X-auth: {{backDoorToken}}

{
  "status": "USED"
}

###  get one semester
GET {{http}}{{host}}{{port}}{{base-url}}/semesters/detail/1
Content-Type: application/json
X-auth: {{backDoorToken}}

###  get current semester
GET {{http}}{{host}}{{port}}{{base-url}}/semesters/current
Content-Type: application/json
X-auth: {{backDoorToken}}

### create
POST {{http}}{{host}}{{port}}{{base-url}}/semesters
Content-Type: application/json
X-auth: {{backDoorToken}}

{
  "name": "221",
  "registerTopicStart": "2021-08-17T00:12:00"
}

### setting current semester
PUT {{http}}{{host}}{{port}}{{base-url}}/semesters/current?id=4
Content-Type: application/json
X-auth: {{backDoorToken}}
