
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/councils
Content-Type: application/json
X-auth: {{backDoorToken}}


###  get by subject department
POST {{http}}{{host}}{{port}}{{base-url}}/councils/example
Content-Type: application/json
X-auth: {{backDoorToken}}

{
  "subjectDepartment": 2
}