
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/topic/assign
Content-Type: application/json

###  get by paging
GET {{http}}{{host}}{{port}}{{base-url}}/topic/assign/paging?page=1&size=5&sort=id&descend=false
Content-Type: application/json

###  get all topic
GET {{http}}{{host}}{{port}}{{base-url}}/topic/assign
Content-Type: application/json

###  search by teacher code
GET {{http}}{{host}}{{port}}{{base-url}}/topic/assign/search/teacher?code=123
Content-Type: application/json

###  search by topic
GET {{http}}{{host}}{{port}}{{base-url}}/topic/assign/search/topic?value=q
Content-Type: application/json

###  create many
POST {{http}}{{host}}{{port}}{{base-url}}/topic/assign/all
Content-Type: application/json

[
  {
    "topic": {
      "code": 123
    }
  }

]

###  create test
POST {{http}}{{host}}{{port}}{{base-url}}/topic/assign
Content-Type: application/json

{
    "guideTeacher": [
        {
            "id": 68,
            "deleted": false,
            "createdAt": "2021-05-04T15:23:41.387447Z",
            "updatedAt": "2021-05-04T15:23:41.387447Z",
            "name": "Teacher",
            "email": null,
            "phone": null,
            "gender": null,
            "subjectDepartment": null,
            "degree": {
                "id": 41,
                "deleted": false,
                "createdAt": "2021-05-01T15:55:23.562561Z",
                "updatedAt": "2021-05-01T15:55:23.562561Z",
                "type": "subjectDepartment",
                "value": "Computer Engineering"
            }
        }
    ],
    "executeStudent": [],
    "topic": {
        "code": "123"
    }
}