
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/topic
Content-Type: application/json

###  get all topic flat
GET {{http}}{{host}}{{port}}{{base-url}}/topic/flat
Content-Type: application/json

###  create one
POST {{http}}{{host}}{{port}}{{base-url}}/topic
Content-Type: application/json

{"major":["62"]}
