
###  get all
GET {{http}}://{{host}}:{{port}}{{base-url}}/topic
Content-Type: application/json

###  create one
POST {{http}}://{{host}}:{{port}}{{base-url}}/topic
Content-Type: application/json

{"major":["62"]}

###  create many
POST {{http}}://{{host}}:{{port}}{{base-url}}/topic/all
Content-Type: application/json

[
  {"code": 1713015, "name": "Đức Anh Tài"}
]