
###  get all
GET {{http}}://{{host}}:{{port}}{{base-url}}/topic/assign
Content-Type: application/json

###  get all topic
GET {{http}}://{{host}}:{{port}}{{base-url}}/topic
Content-Type: application/json

###  create one
POST {{http}}://{{host}}:{{port}}{{base-url}}/topic/assign
Content-Type: application/json

{
  "topic": {
    "topicCode": 123
  }
}
