
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/criterion-roles
Content-Type: application/json
X-auth: {{backDoorToken}}


###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/criterion-roles/detail/1
Content-Type: application/json
X-auth: {{backDoorToken}}

###  get template
GET {{http}}{{host}}{{port}}{{base-url}}/criterion-roles/template
Content-Type: application/json
X-auth: {{backDoorToken}}

###  get template by role
GET {{http}}{{host}}{{port}}{{base-url}}/criterion-roles/template-role?thesis=false&role=review
Content-Type: application/json
X-auth: {{backDoorToken}}