
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/scores
Content-Type: application/json
X-auth: {{backDoorToken}}


###  get by example
POST {{http}}{{host}}{{port}}{{base-url}}/scores/example
Content-Type: application/json
X-auth: {{backDoorToken}}

{
  "settingTemplate": {
    "id": 3
  },
  "topic": {
    "id": "4"
  },
  "teacher": {
    "id": 1
  },
  "student": {
    "id": 1
  }
}

###  get by teacher
POST {{http}}{{host}}{{port}}{{base-url}}/scores/teacher?teacherIds=13,12,11
Content-Type: application/json
X-auth: {{backDoorToken}}

{"topic":{"id":21},"student":{"id":32},"template":{"midSemester":false,"councilRoles":[{"id":3}]}}


###  get by teacher
POST {{http}}{{host}}{{port}}{{base-url}}/scores/teacher?teacherIds=12
Content-Type: application/json
X-auth: {{backDoorToken}}

{"topic":{"id":21},"student":{"id":32},"template":{"midSemester":false,"reviewTeacher":true}}

### get score by topic
GET {{http}}{{host}}{{port}}{{base-url}}/scores/topic/21
Content-Type: application/json
X-auth: {{backDoorToken}}