
###  get all
GET {{http}}://{{host}}:{{port}}{{base-url}}/student
Content-Type: application/json

###  create one
POST {{http}}://{{host}}:{{port}}{{base-url}}/student
Content-Type: application/json

{
  "name": "Teacher",
  "degree": "41"
}

###  create many
POST {{http}}://{{host}}:{{port}}{{base-url}}/student/all
Content-Type: application/json

[
  {"code": 1713015, "name": "Đức Anh Tài"}
]