
###  get all
GET {{http}}{{host}}{{port}}{{base-url}}/teacher
Content-Type: application/json

###  create one
POST {{http}}{{host}}{{port}}{{base-url}}/teacher
Content-Type: application/json

{
  "name": "Teacher",
  "degree": "41"
}

###  get by email example
POST {{http}}{{host}}{{port}}{{base-url}}/teacher/example
Content-Type: application/json

{ "email": "1@hcmut.edu.vn"}

###  create many
POST {{http}}{{host}}{{port}}{{base-url}}/teacher/all
Content-Type: application/json

[
  {"name": "Đức Anh Tài"},
  {"name": "Danh Trí Hiếu"},
  {"name": "Phan Đình Tuệ"},
  {"name": "Trần Thị Vân"}
]