
###  get all
GET {{http}}://{{host}}:{{port}}{{base-url}}/const
Content-Type: application/json

###  get all type
GET {{http}}://{{host}}:{{port}}{{base-url}}/const/types
Content-Type: application/json


###  get by example
POST {{http}}://{{host}}:{{port}}{{base-url}}/const/example
Content-Type: application/json

{ "type": "subjectDepartment"}


###  create const
POST {{http}}://{{host}}:{{port}}{{base-url}}/const/all
Content-Type: application/json

[
  { "type": "subjectDepartment", "value": {"en":"Information System","vi":"Hệ thống thông tin"}},
  { "type": "subjectDepartment", "value": {"en":"Software Technology", "vi":"Công nghệ phần mềm"}},
  { "type": "subjectDepartment", "value": {"en":"Systems and Networks", "vi":"Hệ thống và mạng"}},
  { "type": "subjectDepartment", "value": {"en":"Computer Science","vi":"Khoa học máy tính"}},
  { "type": "subjectDepartment", "value": {"en":"Computer Engineering","vi":"Kỹ thuật máy tính"}},

  { "type": "degree", "value": {"en":"Bachelor", "vi":"Cử nhân"}},
  { "type": "degree", "value": {"en":"Master", "vi":"Thạc sĩ"}},
  { "type": "degree", "value": {"en":"Doctor", "vi":"Tiến sĩ"}},
  { "type": "degree", "value": {"en":"Professor","en":"Giáo sư"}},

  { "type": "major", "value": {"en":"Computer Science","vi":"Khoa học máy tính"}},
  { "type": "major", "value": {"en":"Computer Engineering","vi":"Kỹ thuật máy tính"}},

  { "type": "educationMethod", "value": {"en":"Formal","vi":"Chính quy"}},
  { "type": "educationMethod", "value": {"en":"CLC","vi":"Tiên tiến chất lượng cao"}},

  { "type": "semester", "value": {"en":"201", "vi":"201"}},
  { "type": "semester", "value": {"en":"202", "vi":"202"}},
  { "type": "semester", "value": {"en":"203", "vi":"203"}},

  { "type": "councilRole", "value": {"en":"Boss", "vi":"Chủ tịch"}},
  { "type": "councilRole", "value": {"en":"sub boss", "vi":"Phó chủ tịch"}},
  { "type": "councilRole", "value": {"en":"?", "vi":"Thư ký"}}

]

### delete all
DELETE {{http}}://{{host}}:{{port}}{{base-url}}/const
Content-Type: application/json